---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo
        image: harbor.local/dev/demo-app:0.0.1
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: harbor-creds